name: Deploy

on:
  push:
    branches: [main]

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: |
          wget --output-document=- 'https://github.com/getzola/zola/releases/download/v0.15.3/zola-v0.15.3-x86_64-unknown-linux-gnu.tar.gz' | tar xzf - -C /usr/local/bin 
          wget --output-document=tailwindcss 'https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64' -P ./src
          chmod +x tailwindcss
          make build 

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - id: infrastructure
        run: |
          aws cloudformation deploy --stack-name subpublic-subpublicdotorg --template ./deploy/resources.yaml --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM
          S3_BUCKET=`aws cloudformation describe-stacks --stack-name subpublic-subpublicdotorg --query "Stacks[?StackName=='subpublic-subpublicdotorg'][].Outputs[?OutputKey=='S3Bucket'].OutputValue" --output text`
          CLOUDFORMATION_ID=`aws cloudformation describe-stacks --stack-name subpublic-subpublicdotorg --query "Stacks[?StackName=='subpublic-subpublicdotorg'][].Outputs[?OutputKey=='CloudfrontDistributionId'].OutputValue" --output text`
          echo "::set-output name=s3_bucket::$(echo $S3_BUCKET)"
          echo "::set-output name=cloudfront_dist_id::$(echo $CLOUDFORMATION_ID)"

      - run: |
          aws s3 sync ./build/ s3://${{ steps.infrastructure.outputs.s3_bucket }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ steps.infrastructure.outputs.cloudfront_dist_id }} --paths "/*"
          
